name: C# Syntax Check CI

on: [push, pull_request]

jobs:
  syntax-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Download ReSharper Command Line Tools
      run: wget -qO- https://download.jetbrains.com/resharper/dotUltimate.2020.3.4/JetBrains.ReSharper.CommandLineTools.Unix.2020.3.4.tar.gz | tar xvz

    - name: Download ReSharper Command Line Tools
      run: wget -qO- https://www.jetbrains.com/resharper/download/#section=web-installer | tar xvz


    - name: Upload ReSharper Report
      uses: actions/upload-artifact@v2
      with:
        name: ReSharper Report
        path: resharper-report.xml
