name: C# Syntax Check CI

on: [push, pull_request]

jobs:
  syntax-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Install StyleCop Analyzers
      cd "ApiSocialNetwork/ApiSocialNetwork.csproj"
      run: dotnet add  package StyleCop.Analyzers

    - name: Build with StyleCop
      run: dotnet build --no-restore -c Release