name: C# Syntax Check CI

on: [push, pull_request]

jobs:
  syntax-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'

    - name: Restore dependencies
      run: dotnet restore

    # Здесь больше не нужно устанавливать StyleCop.Analyzers
    # Вместо этого, убедитесь, что ваш проект настроен на использование .NET Analyzers

    - name: Build with .NET Analyzers
      run: dotnet build --no-restore -c Release /p:EnableNETAnalyzers=true
